# Generated by Django 5.1 on 2024-11-26 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('codigo', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=20)),
                ('proveedor', models.CharField(max_length=20)),
                ('total', models.PositiveSmallIntegerField()),
                ('stock', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
