# Generated by Django 5.1 on 2024-12-04 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idproducto', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('idsucursal', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=20)),
                ('idproveedor', models.CharField(max_length=20)),
                ('total', models.PositiveSmallIntegerField()),
                ('stock', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
