# Generated by Django 5.1 on 2024-12-04 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('idcliente', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('telefono', models.CharField(max_length=10)),
                ('direccion', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=100)),
                ('fnacimiento', models.DateField()),
                ('fregistro', models.DateField()),
            ],
        ),
    ]
