# Generated by Django 5.1 on 2024-12-04 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('idempleado', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('idsucursal', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=20)),
                ('telefono', models.CharField(max_length=100)),
                ('correo', models.CharField(max_length=20)),
                ('turno', models.CharField(max_length=20)),
                ('posicion', models.CharField(max_length=20)),
            ],
        ),
    ]
