# Generated by Django 5.1 on 2024-12-04 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('idproveedor', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('telefono', models.CharField(max_length=100)),
                ('correo', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=20)),
                ('paginaweb', models.CharField(max_length=100)),
                ('tipo', models.IntegerField(choices=[(1, 'Fabricante'), (2, 'Mayorista'), (3, 'Menudista')])),
            ],
        ),
    ]
