# Generated by Django 5.1 on 2024-12-03 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedor_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='paginaweb',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='tipo',
            field=models.IntegerField(choices=[(1, 'Fabricante'), (2, 'Mayorista'), (3, 'Menudista')]),
        ),
    ]
