# Generated by Django 5.1 on 2024-12-04 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('idorden', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('idcliente', models.CharField(max_length=20)),
                ('idempleado', models.CharField(max_length=20)),
                ('idsucursal', models.CharField(max_length=20)),
                ('idproducto', models.CharField(max_length=20)),
                ('forden', models.DateField()),
                ('total', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
