# Generated by Django 5.1 on 2024-11-26 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('codigo', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('cliente', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=20)),
                ('forden', models.CharField(max_length=20)),
                ('total', models.PositiveSmallIntegerField()),
                ('metodo_pago', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
