# Generated by Django 5.1 on 2024-12-03 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orden_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='estado',
            field=models.IntegerField(choices=[(1, 'Procesando'), (2, 'Enviando'), (3, 'En entrega')]),
        ),
        migrations.AlterField(
            model_name='orden',
            name='forden',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='orden',
            name='metodo_pago',
            field=models.IntegerField(choices=[(1, 'Tarjeta'), (2, 'Efectivo'), (3, 'Credito')]),
        ),
    ]
